language: c

env: CROSS_COMPILE=i586-mingw32msvc-

# specify MinGW-gcc; however, unset $CC later
compiler: i586-mingw32msvc-gcc

# do not use the exported $CC variable
before_script: "unset CC"

script: "make CC=${CROSS_COMPILE}gcc WINDRES=${CROSS_COMPILE}windres"

after_script:
    - "${CROSS_COMPILE}objdump -p bin/Test.exe"
    - "make STRIP=${CROSS_COMPILE}strip strip"

