language: c

env: CROSS_COMPILE=i586-mingw32msvc-

# do not specify compiler here and do not export $CC
compiler:

# override setup: do nothing
setup:

script: "make CC=${CROSS_COMPILE}gcc WINDRES=${CROSS_COMPILE}windres"

after_script:
    - "${CROSS_COMPILE}objdump -p bin/Test.exe"
    - "make STRIP=${CROSS_COMPILE}strip strip"

