language: c

env: PATH="/usr/i586-mingw32msvc/bin:$PATH"

# specify MinGW-gcc; however, unset $CC later
compiler: gcc

# do not use the exported $CC variable
before_script:
    - "echo path: $PATH"
    - "ls -l /usr/i586-mingw32msvc/bin"
    - "unset CC"

script: "make"

after_script:
    - "objdump -p bin/Test.exe"
    - "make strip"

