language: c

env: WINDRES=i586-mingw32msvc-windres STRIP=i586-mingw32msvc-strip OBJDUMP=i586-mingw32msvc-objdump

compiler: i586-mingw32msvc-gcc

script: make && make strip

after_script: $OBJDUMP -s bin/Test.exe

